### ISSUE TITLE
can you remove the lifetime?

### ISSUE THREAD

**Issue by naturallymitchell** [foundpatterns/patch-rs#2]
to make the bindings simpler

// cc @juchiast

**Comment by juchiast** [comment]
Actually, we can write binding without removing the lifetime, something like this:
``` rust
struct MyPatchParser {
text: Vec<String>,
patch: String,
}

impl MyPatchParser {
    fn process(&self) -> PatchResult<Vec<String>> {
         // new PatchParser
         // call PatchParser.process
    }
}
```

This approach is hacky, I think is preferable to remove the lifetime in `struct PatchParser`.

**Comment by hedgar2017** [comment]
Ok, I'll make the library to consume the data.

**Comment by hedgar2017** [comment]
I've replaced the references with data. It is okay unless a user of the library wants to reuse the data without copying.

**Comment by juchiast** [comment]
@hedgar2017 Thanks. Please public a new version to crates.io

**Comment by dariusc93** [comment]
I forgot to check on this. Yea the lifetimes in this case can be avoided easily in this case. Even if it was there, it can still be worked with easily but it wasnt really necessary to have it since there are alternatives that couldve been used (which was already used now)

**Comment by hedgar2017** [comment]
@juchiast, done
